ipfs/js.ipfs.tech

gatsby-node.js, intl/messages/en.json, intl/messages/pt.json, package-lock.json, package.json, src/pages/home/index.js, src/shared/service-worker/register.js, src/shared/service-worker/sw.js
Integrated [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway) to the `js.ipfs.io`. 
Testing:
- It is necessary to activate the service worker by clicking the button. Afterwards, it is possible to use it as follows:
`{js.ipfs.io}/ipfs/QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o`
`{js.ipfs.io}/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG `
`{js.ipfs.io}/ipfs/QmeYxwj4CwCeGVhwi3xLrmBZUUFQdftshSiGLrTdTnWEVV `
Notes: 
- I added the service worker start button on the Home page 
- As the service worker starts an IPFS node inside it, the user should interact in order to activate it. As previously discussed, it should be a toggle for enabling / disabling. In addition, it would be important to have something that explains the user what it does (maybe a pop …
=> feat: service worker gateway integration

src/shared/data/what-can-you-build/index.js
This PR updates video links used inside accordion component.
=> chore: updated accordion video links

src/shared/components/features-section/feature-item/index.module.css, src/shared/components/hero-section/index.js, src/shared/components/what-can-you-build-section/accordion/index.js
This PR implements auto scroll when a user clicks on an accordion item.
=> fix: add auto scroll when an accordion item is clicked

intl/messages/br.json, intl/messages/en.json, intl/messages/pt.json, src/pages/home/index.js, src/shared/components/banner/index.js, src/shared/components/button/index.js, src/shared/components/carousel/carousel-projects-item/index.js, src/shared/components/carousel/carousel-videos-item/index.js, src/shared/components/carousel/index.js, src/shared/components/community-section/index.js, src/shared/components/features-section/index.js, src/shared/components/footer/index.js, src/shared/components/getting-started-section/index.js, src/shared/components/getting-started-section/steps-list/index.js, src/shared/components/hero-section/index.js, src/shared/components/locales-dropdown/index.js, src/shared/components/navbar/desktop/index.js, src/shared/components/navbar/desktop/index.module.css, src/shared/components/navbar/mobile/index.js, src/shared/components/navbar/mobile/index.module.css, src/shared/components/publications-and-talks-section/index.js, src/shared/components/publications-and-talks-section/videos-list/index.js, src/shared/components/what-are-people-building-section/index.js, src/shared/components/what-are-people-building-section/index.module.css, src/shared/data/features/index.js, src/shared/data/getting-started/index.js, src/shared/data/publications-and-talks/index.js, src/shared/data/what-are-people-building/index.js
This PR updates [`react-intl` files](https://github.com/ipfs/js.ipfs.io/tree/master/intl/messages) structure. Since its structure has changed, the way we use them is slightly different. Thus, this PR updates each file that was accessing these translations keys.
Closes #22
=> fix: rework of intl files structure

intl/messages/en.json, src/shared/data/publications-and-talks/index.js
Couldn't figure out a way to add https://www.elastic.co/videos/unleash-the-distributed-web-by-david-dias :(
=> feat: add talks, part deux

intl/messages/en.json, intl/messages/pt.json, src/shared/components/gateway-section/index.js, src/shared/components/gateway-section/index.module.css
This PR adds a text box message when the service worker is enabled.
=> feat: add gateway message when activated

intl/messages/en.json
=> fix: copy tweaks for en.json

intl/messages/en.json, intl/messages/pt.json, package-lock.json, package.json, src/shared/components/gateway-section/index.js, src/shared/components/gateway-section/index.module.css, src/shared/components/toggle-button/index.js, src/shared/components/toggle-button/index.module.css, src/shared/styles/imports/variables.css
- Add toaster if SW errors
- Disable toggle when activating/deactivating SW
=> feat: sw section improvements

gatsby-config.js, package-lock.json, package.json
Now the website should be compatible with IPFS deployments and dnslink.
Closes #51
=> fix: ensure everything uses relative paths

src/layouts/index.module.css, src/pages/home/index.module.css
=> fix: fix hero being above the footer in firefox

src/shared/components/carousel/carousel-projects-item/index.module.css
=> fix: fix box-shadow being out of place

src/pages/home/index.js, src/shared/components/carousel/index.js, src/shared/components/community-section/index.js, src/shared/components/gateway-section/index.js, src/shared/components/header/index.js, src/shared/components/hero-section/index.js, src/shared/components/locales-dropdown/index.js, src/shared/components/navbar/mobile/index.js, src/shared/components/what-can-you-build-section/accordion/index.js
=> perf: only render contributors hexagons when in viewport

src/shared/components/hero-section/index.js, src/shared/components/hero-section/index.module.css
=> fix: fix hero animation not being paused when offscreen

intl/messages/it.json
Tried to do my best.
Sometimes I use è, sometime `&egrave;`, you want to fix this!
=> Adding Italian translation

src/shared/components/getting-started-section/index.js
=> fix: getting started jsipfs get to cat

package.json, src/shared/components/carousel/carousel-videos-item/index.js, src/shared/components/publications-and-talks-section/videos-list/index.js, src/shared/components/publications-and-talks-section/videos-list/index.module.css, src/shared/components/youtube/index.js, src/shared/components/youtube/index.module.css, src/shared/data/publications-and-talks/index.js
This PR adds a new youtube embed component that lazy load youtube embed using a placeholder thumbnail.
=> feat: add new youtube component

src/shared/data/community/index.js
See: https://github.com/ipfs/contributors/pull/10
Fixes #84.
=> fix: fix contributors glitching in iOS

package-lock.json, package.json
This is temporary until a new version of service-worker-gateway is published: https://github.com/ipfs-shipyard/service-worker-gateway/issues/27
=> fix: update service-worker-gateway to fix svg bug

gatsby-node.js
=> fix: fix /en route not working correctly

src/shared/components/getting-started-section/index.module.css, src/shared/components/syntax-highlighter/index.module.css
This PR increases code blocks width on "Getting Started" section.
Closes #149.
=> chore: increase codeblocks width on 'getting started' section

package-lock.json, package.json
=> chore: upgrade service-worker-gateway

intl/config.js, intl/messages/en.json, intl/messages/pt.json
This PR adds Portuguese translations.
=> feat: add pt-pt translations

README.md
This PR completes readme file. It has instructions related to:
- Development
- Deployment
- Contributions Guidelines
- (How to) Contribute
- License
It closes #157
=> feat: complete readme

src/shared/data/what-you-can-build/index.js
This PR adds the first example of `What you can build with js-ipfs` section
=> chore: add app codesandbox link

src/pages/home/index.js
This PR hides `What you can build` section while it's being tested.
=> chore: hide 'what you can build' section

intl/messages/da.json, intl/messages/en.json, intl/messages/fr.json, intl/messages/it.json, intl/messages/ko-KR.json, intl/messages/pl.json, intl/messages/pt.json, intl/messages/zh-CN.json, src/pages/404/index.js, src/pages/404/index.module.css
This PR adds translations to 404 page.
=> fix: add translations to 404 page

package-lock.json, src/shared/components/what-you-can-build-section/index.module.css
This PR fixes an iOS issue: the iframe width and height were not being set properly. Iframe properties `width: 100%` and `height: 100%` were not respecting their parent size.
Thus, we've fixed it with a trick:
```css
width: 1px;
min-width: 100%;
height: 1px;
min-height: 100%;
```
See [this comment](https://github.com/scottjehl/Device-Bugs/issues/7#issuecomment-171988930).
=> fix: fix iOS bug on iframe

src/shared/components/footer/index.module.css
This is a no-op change against master (`dev`) and won't go out to production.
It will be reverted.
=> no-op change to test build pipeline

src/shared/components/footer/index.module.css
=> remove no-op change

src/pages/home/index.js
Disable what can you build section, as it is not totally ready yet.
=> chore: disable what you can build section

package-lock.json, package.json
Remove malicious code as per [dominictarr/event-stream#116](https://github.com/dominictarr/event-stream/issues/116)
The problem was that [start-server-and-test](https://github.com/bahmutov/start-server-and-test) was using `event-stream>3.3.4`.
=> fix: remove malicious dependency (event-stream)

src/pages/home/index.js
This PR uncomments `What you can build` section so that it becomes visible.
=> chore: uncomment what you can build section

.gitignore
=> chore: add cypress folder to gitignore

package.json
=> chore: remove unused test:e2e:ci script

package.json
=> chore: add default test script

intl/config.js, intl/messages/ko-KR.json, intl/messages/zh-CN.json
This PR adds Chinese language and updates Korean language.
=> feat: add chinese and update korean

src/shared/constants/index.js
This PR updates the website hash.
=> chore: add new website hash

package-lock.json, package.json, src/shared/constants/index.js, src/shared/utils/react-live.js
This release updates both `ipfs` and `service-worker-gateway` version.
`ipfs` -> `v0.36.1`
`service-worker-gateway` -> `v0.1.14`
=> chore: new website release

intl/messages/en.json, src/shared/components/community-section/index.module.css
Fixes https://github.com/ipfs/js.ipfs.io/issues/265.
=> chore: add link to calls

src/shared/components/nav-bar/desktop/index.js, src/shared/components/nav-bar/mobile/index.js
Updating links to IPFS specs from the nav bar
=> Fix specs links

README.md
=> (docs): enabled syntax highlighting

intl/messages/ca.json, intl/messages/cs.json, intl/messages/en.json, intl/messages/fr.json, intl/messages/ja-JP.json, intl/messages/zh-CN.json, src/shared/components/nav-bar/desktop/index.js, src/shared/components/nav-bar/mobile/index.js
Just trying to get the latest from #287 & #288 into production.
=> Push latest changes from master to production

intl/messages/ca.json, intl/messages/cs.json, intl/messages/en.json, intl/messages/fr.json, intl/messages/ja-JP.json, intl/messages/zh-CN.json, src/shared/components/nav-bar/desktop/index.js, src/shared/components/nav-bar/mobile/index.js
Update links to IPFS course on ProtoSchool
=> Update ProtoSchool links

intl/messages/en.json, src/shared/components/community-section/index.js
Context: https://github.com/ipfs/ipfs-docs/pull/787
=> fix: link to community in docs

_redirects
- Add deprecation warning and remove old website
- Add redirection to helia site
- redirect to the helia repo instead of website
- redirect to the docs page about ipfs in js
- redirect with http using redirects file
=> add redirects
