ipfs/js.ipfs.tech

- gatsby-node.js
Webpack build was node oriented and some libs, such as crypto, were not being bundled and do not exist in the browser.
> fix: webpack browser

- .eslintrc.json
- intl/messages/en.json
- intl/messages/pt.json
- src/pages/home/index.js
- src/shared/components/carousel/carousel-item/index.module.css
- src/shared/components/features-section/feature-item/index.module.css
- src/shared/components/getting-started-section/index.module.css
- src/shared/components/getting-started-section/steps-list/index.module.css
- src/shared/components/hero-section/index.module.css
- src/shared/components/locales-dropdown/index.js
- src/shared/components/navbar/desktop/index.js
- src/shared/components/navbar/mobile/index.js
- src/shared/components/publications-and-talks-section/index.js
- src/shared/components/publications-and-talks-section/index.module.css
- src/shared/components/publications-and-talks-section/videos-list/index.js
- src/shared/components/publications-and-talks-section/videos-list/index.module.css
- src/shared/components/publications-and-talks-section/videos-list/remaining-video/index.js
- src/shared/components/publications-and-talks-section/videos-list/remaining-video/index.module.css
- src/shared/components/what-are-people-building-section/index.module.css
- src/shared/components/what-can-you-build-section/accordion/accordion-item/index.js
- src/shared/components/what-can-you-build-section/accordion/accordion-item/index.module.css
- src/shared/components/what-can-you-build-section/accordion/index.js
- src/shared/components/what-can-you-build-section/index.module.css
- src/shared/data/publications-and-talks/index.js
- src/shared/styles/imports/variables.css
This PR implements "Publications & Talks" section. This section must have a set of videos of publications and/or talks and a small description.
For that reason, I've created a `js` file that exports an array of objects. Each object represents one publication/talk and it must have:
- link - `string` - URL to the corresponding video
- description - `string` - ID of `react-intl` translation that holds talk/publication short description
- active - `boolean`- just one of the objects must have this property as `true`. It indicates which video should be highlighted when the page loads.
Thus, if one wants to add a new publication/talk, one just need to: 
1. add a short description on each file of `react-intl` messages; 
2. add a new object to the `array` on …
> feat: add 'publications and talks' section

- gatsby-node.js
- intl/config.js
- src/shared/components/banner/index.module.css
- src/shared/components/header/index.js
- src/shared/components/locales-bar/index.js
- src/shared/components/locales-bar/index.module.css
- src/shared/components/locales-dropdown/index.js
- src/shared/components/locales-dropdown/index.module.css
- src/shared/components/navbar/desktop/index.js
- src/shared/components/navbar/desktop/index.module.css
- src/shared/styles/imports/variables.css
- src/utils/getLocalesUtils.js
This PR updates desktop languages bar to the new design. 
Major changes:
- available locales array on `intl` config file has changed: it was an array of strings (locales acronyms) and it is an object now containing `acronym` and `fullForm`. 
E.g.: 
```javascript
availableLocales: [
{ acronym: 'en', fullForm: 'English' },
{ acronym: 'pt', fullForm: 'Português (PT)' }
]
```
- new `utils` file that exports 3 functions:
1. `getLocalesAcronym` - returns an array containing only the acronyms;
2. `getLocalesFullForm` - returns an array containing only the locales full form;
3. `getIndexByAcronym` - returns the index of a given acronym.
> fix: fix languages design on desktop

- src/shared/components/button/index.module.css
- src/shared/components/carousel/carousel-projects-item/index.js
- src/shared/components/community-section/index.js
- src/shared/components/getting-started-section/index.js
- src/shared/components/hero-section/index.js
- src/shared/components/link/index.js
- src/shared/components/locales-bar/index.js
- src/shared/components/locales-dropdown/index.js
- src/utils/getLocalesUtils.js
This PR fixes both `locales-bar` and `locales-dropdown` menus to change website locale when a user clicks on the locale. 
I've added a new boolean prop (`changeLocale`) to [`Link`](https://github.com/ipfs/js.ipfs.io/blob/master/src/shared/components/link/index.js) component which indicates that locale should be changed instead of linking to other page/section.
> fix: add correct links to locales menu to change website locale

- gatsby-node.js
- package-lock.json
- package.json
It turns out this was an issue with Gatsby.
Basically, Gatsby was changing `resolve.modulesDirectories` which was causing the root `big.js` to be required instead of the one inside `libp2p-switch`.
See https://github.com/webpack/webpack/issues/6538#issuecomment-367324775 for more information.
Fixes #39
> fix: fix libp2p-switch using the wrong big.js

- src/shared/components/button/index.js
- src/shared/components/carousel/carousel-projects-item/index.js
- src/shared/components/carousel/index.js
- src/shared/components/link/index.js
- src/shared/data/what-are-people-building/index.js
This PR changes [`what-are-people-building` array](https://github.com/ipfs/js.ipfs.io/blob/fix/what-are-people-building-projects-array/src/shared/data/what-are-people-building/index.js) in order to allow `link` key that works as an external link for the `learn more` button.
I've also changed [`link`](https://github.com/ipfs/js.ipfs.io/blob/fix/what-are-people-building-projects-array/src/shared/components/link/index.js) component to return an `anchor` tag when we want to use external links.
When we use `to` prop on `link` component we want to do an internal navigation. When we use `href` prop, we want to do an external navigation which returns an `anchor` tag.
> fix: update projects array

- intl/messages/en.json
This PR gives a short version of `Add and retrieve files from anywhere in the IPFS Network`.
Changed from:
- `IPFS is designed to use the power of Content Addressing and Process Addressing to find the nodes in the network that have the content you are looking for and retrieve it. In the same way, you can add any piece of data and other nodes will find it too.`
to: 
- `IPFS uses Content and Process Addressing to find and retrieve content from other nodes in the network. This means any data you add will be reachable by other nodes.`
This PR refs #153.
> chore: rewrite feature

- package-lock.json
- src/pages/home/index.js
- src/shared/components/what-you-can-build-section/index.js
- src/shared/data/what-you-can-build/index.js
This PR fixes a problem related to `codesandbox` running on `Firefox`. Somehow, the IPFS code is conflicting with `codesandbox` as it's throwing internal errors. To avoid it, we host the examples apps on `codepen`. 
`Safari` doesn't allow to open the IPFS repo on embedded examples. Safari considers it a security issue. For that reason, the example apps won't work on this browser.
Examples required by @diasdavid:
Check [this comment](https://github.com/ipfs/js.ipfs.io/issues/179#issuecomment-427086084) for further details.
> feat: re-add what can you build section

- gatsby-node.js
- package-lock.json
- package.json
- src/shared/utils/react-live.js
This PR removes the use of [unpkg](https://github.com/unpkg) to load `ipfs`. 
`ipfs` was added as a dependency and it is bundled on separate chunks.
Closes #152.
> fix: bundle ipfs module

- src/shared/components/what-you-can-build-section/index.js
This PR adds [`react-intersection-observer`](https://github.com/researchgate/react-intersection-observer) in order to lazy load `iframe` content on `What you can build` section. It'll help us to avoid unnecessary loads on page load.
> chore: lazy load iframe content on 'what you can build' section

- package-lock.json
- package.json
This PR fixes a problem related to [`husky`](https://www.npmjs.com/package/husky) which is: husky does not overwrite existing hooks.
To make it work, on `postinstall` script I'm currently deleting all the hooks using [`rimraf`](https://github.com/isaacs/rimraf) and then reinstall all the hooks.
So, `postbuild` script looks like:
```
"scripts": {
(...),
"postinstall": "rimraf .git/hooks/* && node node_modules/husky/husky.js install",
(...)
}
```
> fix: husky not overriding existing hooks

- package-lock.json
- package.json
This PR updates [service-worker-gateway](https://github.com/ipfs-shipyard/service-worker-gateway) to `v0.1.11`.
This PR closes #207 as it:
- updates `js-ipfs` version from `v0.31.7` to `v0.33.1`
- fixes empty CIDs list on Firefox even after loading some examples
- updates `repoSize` info. It's only showing repo size now on `/stats` page.
> chore: update service worker gateway version

- gatsby-config.js
- package-lock.json
- package.json
This PR adds [gatsby-plugin-google-tag](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-google-gtag) so that we can send event data to Google Analytics.
> feat: add gatsby-plugin-google-tag (gtag.js)

- src/layouts/index.js
This implements the IPFS Camp ribbon banner 💅
Currently only visible on larger screen layouts however I may also add a smaller screen variant once I've had chance to evaluate the analytics.
ref: protocol/2019-ipfs-camp#13
> feat: include ipfs-camp ribbon

- src/shared/constants/index.js
This PR updates [js.ipfs.io](https://js.ipfs.io/) hash to `QmTfgXTG2PN15mQEo7VCbSfc8RbJd9stabBcE4hzKBuiMX`
> chore: update website hash

- .circleci/config.yml
Remove unused dev domain from CI, hoping to make it green when merging to `master` ✅
> chore: remove unused dev domain from CI

- intl/messages/en.json
- src/shared/components/getting-started-section/index.js
Add link to ProtoSchool tutorials. 
Remove references to libp2p project and replace with IPFS. Was unable to add link to calls due to z-index issue to be addressed in later PR.
Paired w @fsdiogo @lidel
> chore: add protoschool link & fix libp2p references

- package-lock.json
- package.json
- src/shared/utils/react-live.js
Updates `ipfs` dep to `^0.38.0` which can take strings as input to `ipfs.add` - no need to convert to a `Buffer` first.
> docs: update examples to use strings

- src/shared/components/getting-started-section/index.js
- src/shared/components/nav-bar/desktop/index.js
- src/shared/components/nav-bar/mobile/index.js
The examples have moved inside the js-ipfs repo, links updated to the new location
> fix: broken tutorial links

- .tx/config
- intl/config.js
- intl/messages/ca.json
- intl/messages/cs.json
- intl/messages/ja-JP.json
- src/shared/components/locales-bar/index.js
- src/shared/components/locales-dropdown/index.js
This PR:
- adds new languages translated by community on Transifex  (cc #276)
- [ja-JP](https://bafybeihopmmsakcjyd2p4mibxz5xctebuc555uraaxodjnndy2zjrdv3kq.ipfs.dweb.link/ja-JP/)
- [cs](https://bafybeihopmmsakcjyd2p4mibxz5xctebuc555uraaxodjnndy2zjrdv3kq.ipfs.dweb.link/cs/)
- [ca](https://bafybeihopmmsakcjyd2p4mibxz5xctebuc555uraaxodjnndy2zjrdv3kq.ipfs.dweb.link/ca/)
- fixes the link to translation instructions
> feat(i18n): add ja-JP, cs and ca

- src/shared/components/nav-bar/desktop/index.js
- src/shared/components/nav-bar/mobile/index.js
Better safe than sorry: this PR isolates the third-party iframe from js.ipfs.io Origin.
Ref. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
> fix: sanbox iframe with github star count

- src/shared/components/getting-started-section/index.js
- src/shared/components/nav-bar/desktop/index.js
- src/shared/components/nav-bar/mobile/index.js
The tutorials link on js.ipfs.io links to https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs/examples#js-ipfs-examples-and-tutorials which has been moved to https://github.com/ipfs/js-ipfs/tree/master/examples#js-ipfs-examples-and-tutorials
> fix broken tutorials-link

- intl/messages/ca.json
- intl/messages/cs.json
- intl/messages/en.json
- intl/messages/fr.json
- intl/messages/ja-JP.json
- intl/messages/zh-CN.json
Updates ProtoSchool link to go to a filtered list of IPFS tutorials only rather than displaying all ProtoSchool tutorials.
Note that I had to use `--no-verify` to get this push through, but probably just a problem with my own machine.
> chore: update ProtoSchool link

- src/shared/components/nav-bar/desktop/index.js
- src/shared/components/nav-bar/mobile/index.js
This PR changes the Tutorials link in desktop and mobile versions of the js.ipfs.io nav to direct to the new IPFS course on ProtoSchool (a filtered list of tutorials related to IPFS, where all coding challenges are js-ipfs coding challenges) rather than the directory of examples and tutorials at https://github.com/ipfs/js-ipfs/tree/master/examples#js-ipfs-examples-and-tutorials. (That directory remains linked from the Learn More button.)
Per my discussion with @johnnymatthews, this is intended as a temporary fix for the next few weeks while the examples in that directory are ported to docs.ipfs.io where the structure will then look something like this: 
```
Integrations
Go-IPFS
...
JS-IPFS
Install
Features
**Tutorials**
<ALL THE EXAMPLES FROM ipfs/js-ipfs>
ProtoSchool --> (external link) …
```
> Update tutorials nav link

- README.md
Instructions were confusing and people opened PR which should be done only by admin/maintainer  (https://github.com/ipfs/js.ipfs.io/pull/290, https://github.com/ipfs/js.ipfs.io/pull/291, https://github.com/ipfs/js.ipfs.io/pull/276)
This clarifies that and emphasizes regular translators work only on Transifex.
> docs(README): clarify i18n flow

- src/shared/components/community-section/index.js
The old link was pointed to a Twitter account that just has a post pointing to the new one.
Figure it makes sense to just point to the active account.
> Updated Twitter link to active IPFS account.

- src/shared/components/getting-started-section/index.js
Fix broken link for button "LEARN MORE" in "GETTING STARTED" visible in the home-page.
> docs: Fix broken link for button "LEARN MORE" in "GETTING STARTED"
